# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTAZq1fhiKsdsfEeZqbhSqCjJjCtZc0G
"""

def calculadora(num1, num2, operacao):
  #### soma #######
    if operacao == 1:
        return num1 + num2

  #### subtração ####
    elif operacao == 2:
        return num1 - num2

  #### multiplicação #####
    elif operacao == 3:
        return num1 * num2

  #### divisão #######
    elif operacao == 4:
        if num2 != 0:
            return num1 / num2
        else:
            return "Erro: Não é possível dividir por zero. Por favor, insira um número diferente."

    else:
        return "Erro: Operação inválida. Por favor, escolha uma operação entre 1 e 4."


resultado = calculadora(3, 5, 1)
print(resultado)

resultado = calculadora(3, 5, 3)
print(resultado)

resultado = calculadora(9, 5, 5)
print(resultado)

resultado = calculadora(10, 0, 4)
print(resultado)